run:
    deadline: 10m
    modules-download-mode: vendor

linters:
  enable-all: false
  enable:
    - deadcode
    - dupl
    - errcheck
    - goconst
    - gofmt
    - golint
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - bodyclose
    - gocritic
    - gocognit
    - gocyclo
issues:
  max-per-linter: 0
  max-same-issues: 0
