name: build
on: [push, pull_request]
jobs:
  build:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.51.2/install.sh | sh -s -- -b $(go env GOPATH)/bin 
          $(go env GOPATH)/bin/golangci-lint run -v

      - name: Run tests
        run: make test
